//tag::ref-doc[]
= processor-utah-pricelist-parser

The `utah-pricelist-parser` processor examines a stream of store products / prices and republishes on a topic containing category information.  This allows downstream consumers to selectively consume product information based on category using topic filters.


== Input

=== Headers

* N/A

=== Payload

* `com.solace.demo.utahdabc.datamodel.Product` from a price list loader processor.

== Output

=== Headers

* N/A

=== Payload

* The same payload (`com.solace.demo.utahdabc.datamodel.Product`) provided to the input stream.  Note that the product is also published on a dynamically categorized topic.

== Options

The **$$utah-pricelist-parser$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$utah.pricelist.parser.publish-topic-prefix$$:: $$Topic prefix to use when publishing categorized products$$ *($$String$$, default: `$$product/$$`)*
//end::configuration-properties[]


== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar utah-pricelist-parser-processor-solace-0.0.1.BUILD-SNAPSHOT.jar --solace.java.host=192.168.65.3 --solace.java.msgVpn=default --solace.java.clientUsername=default --solace.java.clientPassword=default --spring.cloud.stream.bindings.input.destination=utah.pricelist.parser --spring.cloud.stream.bindings.input.group=group --spring.cloud.stream.solace.bindings.input.consumer.queueAdditionalSubscriptions=product/utah/all --spring.cloud.stream.bindings.output.destination=utah/pricelist/parser --solace.java.apiProperties.generate_sender_id=true --solace.java.apiProperties.generate_sequence_numbers=true --solace.java.apiProperties.generate_send_timestamps=true
```

//end::ref-doc[]
